---
- name: install packages
  apt: 
    name: ['redis-tools', 'redis-server']
    update_cache: true
    state: present

- name: For Redis change file /etc/sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf    
    line: 'vm.overcommit_memory = 1'
    create: yes
- name: For Redis change file /etc/rc.local
  lineinfile:
    path: /etc/rc.local    
    line: 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'
    create: yes
- name: Configure the redis cnf file with hosts
  template: 
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
  notify: restart redis-server
- name: Autostart Redis
  shell: update-rc.d redis-server defaults